# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: overtime_development
  username: postgres
  password: omnipod

 
test:
  <<: *default
  database: overtime_test
  username: postgres
  password: omnipod 



production:
  <<: *default
  database: overtime_production
  username: overtime
  password: <%= ENV['OVERTIME_DATABASE_PASSWORD'] %>
